"""create gmail message label view

Revision ID: d58dbb7501bf
Revises: e10102ba7fc0
Create Date: 2024-10-25 23:32:13.670685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58dbb7501bf'
down_revision: Union[str, None] = 'e10102ba7fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


create_view_query = """
CREATE OR REPLACE VIEW gmail.message_label_view AS
select
	ml.message_id,
	ml.label_id,
	ll.name,
	ll.type as label_type
from gmail.message_label ml
join gmail.label ll on ml.label_id = ll.label_id
"""

delete_view_query = """
DROP VIEW IF EXISTS gmail.message_label_view;
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(create_view_query)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(delete_view_query)
    # ### end Alembic commands ###
