"""create gmail label table

Revision ID: d40325d28363
Revises: fb863fd261d3
Create Date: 2024-10-24 01:26:02.907469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd40325d28363'
down_revision: Union[str, None] = '3f0703c9c5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('label_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_id'),
    sa.UniqueConstraint('name'),
    schema='gmail'
    )
    op.create_index('idx_label_label_id', 'label', ['label_id'], unique=True, schema='gmail')
    op.create_index('idx_label_name', 'label', ['name'], unique=True, schema='gmail')
    op.create_index(op.f('ix_gmail_label_id'), 'label', ['id'], unique=False, schema='gmail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_label_id'), table_name='label', schema='gmail')
    op.drop_index('idx_label_name', table_name='label', schema='gmail')
    op.drop_index('idx_label_label_id', table_name='label', schema='gmail')
    op.drop_table('label', schema='gmail')
    # ### end Alembic commands ###
